#!/usr/bin/env bash

if [ -n "$AWS_BUCKET" ]; then
  cat << EOF > .s3cfg
[default]
access_key = ${AWS_ACCESS_KEY}
secret_key = ${AWS_SECRET_KEY}
EOF
  if [ -d world ]; then
    s3cmd sync world/ s3://${AWS_BUCKET}/world/
  else
    mkdir -p world
    cd world
    s3cmd get --recursive s3://${AWS_BUCKET}/world/
    cd ..
  fi
  rm .s3cfg
fi

#dropbox
if [ -n "$DROPBOX" ]; then
[default]
access_token = ${DBCONFIG}
App_key = ${DBKEY}
App_secret = ${DBSEC}

curl -X POST https://content.dropboxapi.com/2/files/upload \
    --header "Authorization: Bearer "${DBCONFIG}"" \
    --header "Dropbox-API-Arg: {\"path\": \"/World\",\"mode\": \"add\",\"autorename\": true,\"mute\": false,\"strict_conflict\": false}" \
    --header "Content-Type: application/octet-stream" \
    --data-binary @local_file.txt
{
    "path": "/world,
    "mode": "add",
    "autorename": true,
    "mute": false,
    "strict_conflict": false
}
